### ISSUE TITLE
Default manifest.xml

### ISSUE THREAD

**Issue by applemuncy** [ubports/wiki.ubports.com#1]
This is a suggestion about including information about the default manifest.xm .
Perhaps linking to
https://developer.android.com/guide/topics/manifest/manifest-intro.html

**Comment by UniversalSuperBox** [comment]
@applemuncy is referencing "Setting up your Tree", created in this commit:

#a9a5cab0d780e82fc64dcdecb4846930103b0045

**Comment by applemuncy** [comment]
Yes.

**Comment by applemuncy** [comment]
After looking at the link I supplied, I don't think it's suitable. 
So I don't know where to find useful information.

**Comment by UniversalSuperBox** [comment]
I've linked to the Cyanogenmod page on the manifest.

https://github.com/ubports/wiki.ubports.com/commit/4e3d6cc777d5f6f91b1afb902207145e96bdbc75
