### ISSUE TITLE
Bugtracker for the web browser ?

### ISSUE THREAD

**Issue by lduboeuf** [ubports/wiki.ubports.com#13]
In  https://wiki.ubports.com/wiki/UBports-Bug-Trackers , didn't find any link to bug tracker for the web browser

**Comment by NeoTheThird** [comment]
Thank you for reporting, i fixed it. For the record, the bugs are tracked here: https://github.com/ubports/webbrowser-component

Since Oxide is so tightly integrated in the system, you could also report bugs on https://github.com/ubports/ubports-touch.
