### ISSUE TITLE
'Writing a Good Bug Report' correction - Github doesn't allow .log files

### ISSUE THREAD

**Issue by padraic7a** [ubports/wiki.ubports.com#14]
I just posted this bug report: https://github.com/ubports/ubports-touch/issues/114

Following the instructions here: https://wiki.ubports.com/wiki/Writing-a-Good-Bug-Report

When I tried to attach a .log file it was rejected.

![file_rejection](https://user-images.githubusercontent.com/3010391/27205969-090105b6-522c-11e7-8ce9-01296ae953f9.png)

**Comment by UniversalSuperBox** [comment]
Thanks for the report! I've just changed the file names to fix the issue.
