### ISSUE TITLE
ubuntu-device-flash command on How-to-flash-existing-ubuntu-touch-devices-with-Ubports-images.md

### ISSUE THREAD

**Issue by altpapier** [ubports/wiki.ubports.com#15]
Hi, 
I am just flashing my Aquaris 4.5 for the first time with the stable UBPorts image, using the instruction of the wiki. The PC I am using for flashing is running debian testing / stretch.

    sudo ubuntu-device-flash --server=https://system-image.ubports.com/ touch \
    --channel=15.04/stable --bootstrap \
    --recovery-image=[Downloaded adb recovery image]

the output of this command was:
2017/06/16 23:43:29 Expecting the device to be in the bootloader... waiting
2017/06/16 23:43:49 Device is |krillin|
2017/06/16 23:43:50 Flashing version 1 from 15.04/stable channel and server https://system-image.ubports.com/ to device krillin
**2017/06/16 23:43:50 mkdir /root/.cache: permission denied**

running the command without "sudo" helped (see https://askubuntu.com/questions/889895/failure-during-installation-of-ubuntu-phone)

kind regards,
Chris

**Comment by NeoTheThird** [comment]
Moving all issues to the new tracker over at ubports/ubports.com
