### ISSUE TITLE
help with Installing-Your-Build-With-Rootstock.md 

### ISSUE THREAD

**Issue by applemuncy** [ubports/wiki.ubports.com#3]
So in prep for installing my build I'm reading the insides of rootstock-touch-install and I see the option -c --custom that must be how one uses the files like vivid-preinstalled-touch-armhf.custom.tar.gz that seems to be Ubuntu's collection of touch apps. 

Is it a conscious choice that Ubports is not using the custom file? But maybe Ubports is using it and mistaken?

And also, I do not understand why rootstock-touch-install insists that the custom file is tar.xz rather than tar.gz ?

**Comment by UniversalSuperBox** [comment]
The custom.tar.gz file is for phone manufacturers to install their own apps on an Ubuntu Touch device beyond what is included by default. It is not useful during the debugging stage of a port.

Source: http://sturmflut.github.io/ubuntu/touch/2015/05/06/hacking-ubuntu-touch-part-2-devices-and-images/

**Comment by applemuncy** [comment]
So Terminal is the one important app of the Ubuntu custom standard. So when adb isn't working and network isn't working or loading terminal by Ubuntu play store fails just how do you talk to your installed system?
