### ISSUE TITLE
Github Login does not work

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/wiki.ubports.com#9]
It is impossible to log in to the wiki with GitHub. The Google-login works.

## Steps to reproduce this issue:

- Go to https://wiki.ubports.com/login?destination=%2Fwiki%2FHome
- click "Sign in with GitHub"

## Result

`<h1>Forbidden</h1>`

**Comment by UniversalSuperBox** [comment]
This has finally been fixed! Log away!
